-- MySQL Script generated by MySQL Workbench
-- 01/04/16 12:50:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema markup
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `markup` ;

-- -----------------------------------------------------
-- Schema markup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `markup` DEFAULT CHARACTER SET utf8 ;
USE `markup` ;

-- -----------------------------------------------------
-- Table `markup`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`categorias` ;

CREATE TABLE IF NOT EXISTS `markup`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`subcategorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`subcategorias` ;

CREATE TABLE IF NOT EXISTS `markup`.`subcategorias` (
  `id_subcategoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_subcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`produtos` ;

CREATE TABLE IF NOT EXISTS `markup`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `fk_categoria` INT NULL DEFAULT NULL,
  `fk_sub_categoria` INT NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `descricao_abreviada` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(150) NULL DEFAULT NULL,
  `especificacao` VARCHAR(150) NULL DEFAULT NULL,
  `cod_ncm` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_ean` VARCHAR(45) NULL DEFAULT NULL,
  `secao` VARCHAR(45) NULL DEFAULT NULL,
  `garantia_da_loja_em_dias` INT NULL DEFAULT NULL,
  `volume_m3` VARCHAR(45) NULL DEFAULT NULL,
  `peso_em_gramas` INT NULL DEFAULT NULL,
  `unidades_pacote` INT NULL DEFAULT NULL,
  `venda_fracionada` ENUM('SIM', 'NAO') NULL DEFAULT NULL,
  `tipo_venda_fracionada` ENUM('KILO', 'UNIDADE', 'LITRO') NULL DEFAULT NULL,
  `valor_fracionado` VARCHAR(45) NULL DEFAULT NULL,
  `quant_min_estoque` INT NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `lucro` VARCHAR(45) NULL DEFAULT NULL,
  `valor_de_custo` VARCHAR(45) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `valor_final` VARCHAR(45) NULL DEFAULT NULL,
  `markup` VARCHAR(45) NULL DEFAULT NULL,
  `valor_icms_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_ipi_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_pis_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_cofins_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_csll_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_irpj_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_comissao_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_administrativa_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_issqn_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_cfop` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_categoria_idx` (`fk_categoria` ASC),
  INDEX `fk_sub_categoria_idx` (`fk_sub_categoria` ASC),
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `markup`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_categoria`
    FOREIGN KEY (`fk_sub_categoria`)
    REFERENCES `markup`.`subcategorias` (`id_subcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`municipios` ;

CREATE TABLE IF NOT EXISTS `markup`.`municipios` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `markup`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(250) NULL DEFAULT NULL,
  `num` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(250) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `fk_municipio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_municipio_idx` (`fk_municipio` ASC),
  CONSTRAINT `fk_municipio`
    FOREIGN KEY (`fk_municipio`)
    REFERENCES `markup`.`municipios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`clientes` ;

CREATE TABLE IF NOT EXISTS `markup`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL DEFAULT NULL,
  `nome_fantasia` VARCHAR(250) NULL DEFAULT NULL,
  `sexo` ENUM('MASC', 'FEM') NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `tel_1` VARCHAR(45) NULL DEFAULT NULL,
  `tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `fk_endereco` INT NULL DEFAULT NULL,
  `rg_ie` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` ENUM('PF', 'PJ') NULL DEFAULT NULL,
  `inscricao_municipal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`, `cpf_cnpj`),
  INDEX `fk_endereco_idx` (`fk_endereco` ASC),
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `markup`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`convenios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`convenios` ;

CREATE TABLE IF NOT EXISTS `markup`.`convenios` (
  `id_convenio` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `valor_desconto` VARCHAR(45) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `inicio` DATE NULL DEFAULT NULL,
  `fim` DATE NULL DEFAULT NULL,
  `tipo_desconto` ENUM('VALOR', 'PORCENTO', 'TOTAL') NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  PRIMARY KEY (`id_convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`cargos` ;

CREATE TABLE IF NOT EXISTS `markup`.`cargos` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`colaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`colaboradores` ;

CREATE TABLE IF NOT EXISTS `markup`.`colaboradores` (
  `id_colaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `tel_interno` VARCHAR(45) NULL DEFAULT NULL,
  `tel_pessoal` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `valor_comissao` VARCHAR(45) NULL DEFAULT NULL,
  `fk_cargo` INT NULL DEFAULT NULL,
  `fk_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_colaborador`),
  INDEX `fk_cargo_1_idx` (`fk_cargo` ASC),
  CONSTRAINT `fk_cargo_1`
    FOREIGN KEY (`fk_cargo`)
    REFERENCES `markup`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`caixas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`caixas` ;

CREATE TABLE IF NOT EXISTS `markup`.`caixas` (
  `id_caixa` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NULL DEFAULT NULL,
  `data_abertura` DATE NULL DEFAULT NULL,
  `hora_abertura` INT NULL DEFAULT NULL,
  `min_abertura` INT NULL DEFAULT NULL,
  `data_fechamento` DATE NULL DEFAULT NULL,
  `hora_fechamento` INT NULL DEFAULT NULL,
  `min_fechamento` INT NULL DEFAULT NULL,
  `fk_user_abertura` INT NULL DEFAULT NULL,
  `fk_user_fechamento` INT NULL DEFAULT NULL,
  `valor_inicial` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('ABERTO', 'FECHADO') NULL DEFAULT NULL,
  `valor_fechamento` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_terminal` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_caixa`),
  INDEX `fk_user_abertura_1_idx` (`fk_user_abertura` ASC),
  INDEX `fk_user_fechamento_1_idx` (`fk_user_fechamento` ASC),
  CONSTRAINT `fk_user_abertura_1`
    FOREIGN KEY (`fk_user_abertura`)
    REFERENCES `markup`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_fechamento_1`
    FOREIGN KEY (`fk_user_fechamento`)
    REFERENCES `markup`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`compras` ;

CREATE TABLE IF NOT EXISTS `markup`.`compras` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `quant_total` INT NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `valor_total` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('PENDENTE', 'FECHADO', 'CANCELADO') NULL DEFAULT NULL,
  `data_compra` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`credores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`credores` ;

CREATE TABLE IF NOT EXISTS `markup`.`credores` (
  `id_credor` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `tel_1` VARCHAR(45) NULL DEFAULT NULL,
  `tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `tipo` ENUM('PF', 'PJ') NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  PRIMARY KEY (`id_credor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`grupos_fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`grupos_fornecedores` ;

CREATE TABLE IF NOT EXISTS `markup`.`grupos_fornecedores` (
  `id_grupo_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_grupo_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`fornecedores` ;

CREATE TABLE IF NOT EXISTS `markup`.`fornecedores` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `fk_grupo` INT NULL DEFAULT NULL,
  `fk_endereco` INT NULL DEFAULT NULL,
  `nome_razao` VARCHAR(250) NULL DEFAULT NULL,
  `tipo` ENUM('PF','PJ') NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `nome_fantasia_apelido` VARCHAR(250) NULL DEFAULT NULL,
  `tel_1` VARCHAR(45) NULL DEFAULT NULL,
  `tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `nome_responsavel` VARCHAR(250) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `rg_ie` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fornecedor`),
  INDEX `fk_endereco_idx` (`fk_endereco` ASC),
  INDEX `fk_grupo_fornecedor_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_grupo_fornecedor`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `markup`.`grupos_fornecedores` (`id_grupo_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_fornecedor`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `markup`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`movimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`movimentos` ;

CREATE TABLE IF NOT EXISTS `markup`.`movimentos` (
  `id_movimento` INT NOT NULL AUTO_INCREMENT,
  `fk_cliente` INT NULL DEFAULT NULL,
  `fk_vendedor` INT NULL DEFAULT NULL,
  `fk_convenio` INT NULL DEFAULT NULL,
  `fk_caixa` INT NULL DEFAULT NULL,
  `fk_recebimento_crediario` INT NULL DEFAULT NULL,
  `data_abertura` DATE NULL DEFAULT NULL,
  `hora_abertura` INT NULL DEFAULT NULL,
  `min_abertura` INT NULL DEFAULT NULL,
  `data_fechamento` DATE NULL DEFAULT NULL,
  `hora_fechamento` INT NULL DEFAULT NULL,
  `min_fechamento` INT NULL DEFAULT NULL,
  `valor_final` VARCHAR(45) NULL DEFAULT NULL,
  `desconto` VARCHAR(45) NULL DEFAULT NULL,
  `status_pagamento` ENUM('ABERTO','FECHADO', 'CANCELADO') NULL DEFAULT NULL,
  `valor_bruto` VARCHAR(45) NULL DEFAULT NULL,
  `motivo_cancelamento` VARCHAR(250) NULL DEFAULT NULL,
  `valor_comissao` VARCHAR(45) NULL DEFAULT NULL,
  `sinc_server` ENUM('SIM', 'NAO') NULL DEFAULT NULL,
  `cpf_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `desconto_convenio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_movimento`),
  INDEX `fk_cliente_idx` (`fk_cliente` ASC),
  INDEX `fk_caixa_idx` (`fk_caixa` ASC),
  INDEX `fk_vendedor_idx` (`fk_vendedor` ASC),
  INDEX `fk_recebimento_crediario_idx` (`fk_recebimento_crediario` ASC),
  INDEX `fk_convenio_1_idx` (`fk_convenio` ASC),
  CONSTRAINT `fk_cliente_1`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `markup`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenio_1`
    FOREIGN KEY (`fk_convenio`)
    REFERENCES `markup`.`convenios` (`id_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_1`
    FOREIGN KEY (`fk_caixa`)
    REFERENCES `markup`.`caixas` (`id_caixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_1`
    FOREIGN KEY (`fk_vendedor`)
    REFERENCES `markup`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recebimento_crediario`
    FOREIGN KEY (`fk_recebimento_crediario`)
    REFERENCES `markup`.`entrada_saida` (`id_entrada_saida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`entrada_saida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`entrada_saida` ;

CREATE TABLE IF NOT EXISTS `markup`.`entrada_saida` (
  `id_entrada_saida` INT NOT NULL AUTO_INCREMENT,
  `fk_credor` INT NULL DEFAULT NULL,
  `fk_cliente` INT NULL DEFAULT NULL,
  `fk_compra` INT NULL DEFAULT NULL,
  `fk_colaborador` INT NULL DEFAULT NULL,
  `referente` VARCHAR(250) NULL DEFAULT NULL,
  `tipo_pagamento` ENUM('UNICO', 'PARCELADO', 'FIXO') NULL DEFAULT NULL,
  `valor_entrada` VARCHAR(45) NULL DEFAULT NULL,
  `valor_total` VARCHAR(45) NULL DEFAULT NULL,
  `porcento_comissao` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `num_de_parcelas` INT NULL DEFAULT NULL,
  `porcento_multa` VARCHAR(45) NULL DEFAULT NULL,
  `porcento_juros` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('ABERTO', 'EM PAGAMENTO',  'FECHADO') NULL DEFAULT NULL,
  `tipo` ENUM('ENTRADA', 'SAIDA') NULL DEFAULT NULL,
  `primeiro_vencimento` DATE NULL DEFAULT NULL,
  `fk_movimento` INT NULL DEFAULT NULL,
  `fk_fornecedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_entrada_saida`),
  INDEX `fk_vendedor_idx` (`fk_colaborador` ASC),
  INDEX `fk_compra_idx` (`fk_compra` ASC),
  INDEX `fk_credor_idx` (`fk_credor` ASC),
  INDEX `fk_cliente_idx` (`fk_cliente` ASC),
  INDEX `fk_movimento_5_idx` (`fk_movimento` ASC),
  INDEX `fk_fornecedor_8_idx` (`fk_fornecedor` ASC),
  CONSTRAINT `fk_colaborador_5`
    FOREIGN KEY (`fk_colaborador`)
    REFERENCES `markup`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_1`
    FOREIGN KEY (`fk_compra`)
    REFERENCES `markup`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credor_3`
    FOREIGN KEY (`fk_credor`)
    REFERENCES `markup`.`credores` (`id_credor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_2`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `markup`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_5`
    FOREIGN KEY (`fk_movimento`)
    REFERENCES `markup`.`movimentos` (`id_movimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_8`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `markup`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`unidade_empresarial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`unidade_empresarial` ;

CREATE TABLE IF NOT EXISTS `markup`.`unidade_empresarial` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(250) NULL DEFAULT NULL,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `subtitulo` VARCHAR(250) NULL DEFAULT NULL,
  `nome_completo` VARCHAR(250) NULL DEFAULT NULL,
  `tel_1` VARCHAR(45) NULL DEFAULT NULL,
  `tel_2` VARCHAR(45) NULL DEFAULT NULL,
  `site` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `pais_padrao` VARCHAR(250) NULL DEFAULT NULL,
  `itens_por_pagina` INT NULL DEFAULT NULL,
  `saldo_inicial_caixa` VARCHAR(45) NULL DEFAULT NULL,
  `desconto_padrao` VARCHAR(45) NULL DEFAULT NULL,
  `porcento_lucro_produto` VARCHAR(45) NULL DEFAULT NULL,
  `quant_min_estoque` INT NULL DEFAULT NULL,
  `quant_min_inventario` INT NULL DEFAULT NULL,
  `porcento_multa_padrao` VARCHAR(45) NULL DEFAULT NULL,
  `porcento_juros_ao_mes_padrao` VARCHAR(45) NULL DEFAULT NULL,
  `num_dias_mes_comercial` INT NULL DEFAULT NULL,
  `porcento_comissao_padrao` VARCHAR(45) NULL DEFAULT NULL,
  `fk_endereco` INT NULL DEFAULT NULL,
  `frase_lema` VARCHAR(250) NULL DEFAULT NULL,
  `cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `cnae` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_estadual` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_municipal` VARCHAR(45) NULL DEFAULT NULL,
  `nome_fantasia` VARCHAR(250) NULL DEFAULT NULL,
  `codigo_municipio_padrao` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidade`),
  INDEX `fk_endereco_idx` (`fk_endereco` ASC),
  CONSTRAINT `fk_endereco_unidade`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `markup`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`movimento_x_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`movimento_x_produto` ;

CREATE TABLE IF NOT EXISTS `markup`.`movimento_x_produto` (
  `id_mov_x_prod` INT NOT NULL AUTO_INCREMENT,
  `fk_movimento` INT NULL DEFAULT NULL,
  `fk_produto` INT NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_mov_x_prod`),
  INDEX `fk_movimento_idx` (`fk_movimento` ASC),
  INDEX `fk_produto_1_idx` (`fk_produto` ASC),
  CONSTRAINT `fk_movimento_1`
    FOREIGN KEY (`fk_movimento`)
    REFERENCES `markup`.`movimentos` (`id_movimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `markup`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`historico_de_precos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`historico_de_precos` ;

CREATE TABLE IF NOT EXISTS `markup`.`historico_de_precos` (
  `id_historico_preco` INT NOT NULL AUTO_INCREMENT,
  `fk_produto` INT NULL DEFAULT NULL,
  `valor_bruto` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_historico_preco`),
  INDEX `fk_produto_idx` (`fk_produto` ASC),
  CONSTRAINT `fk_produto_historico`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `markup`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`parcelas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`parcelas` ;

CREATE TABLE IF NOT EXISTS `markup`.`parcelas` (
  `id_parcela` INT NOT NULL AUTO_INCREMENT,
  `fk_entrada_saida` INT NULL DEFAULT NULL,
  `valor_parcela` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('ABERTO', 'FECHADO') NULL DEFAULT NULL,
  `valor_final` VARCHAR(45) NULL DEFAULT NULL,
  `data_vencimento` DATE NULL DEFAULT NULL,
  `indice` INT NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_parcela`),
  INDEX `fk_a_receber_idx` (`fk_entrada_saida` ASC),
  CONSTRAINT `fk_a_receber`
    FOREIGN KEY (`fk_entrada_saida`)
    REFERENCES `markup`.`entrada_saida` (`id_entrada_saida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`inventario` ;

CREATE TABLE IF NOT EXISTS `markup`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `cod_ean` VARCHAR(45) NULL DEFAULT NULL,
  `valor_custo` VARCHAR(45) NULL DEFAULT NULL,
  `quant_min_inventario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_inventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`retiradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`retiradas` ;

CREATE TABLE IF NOT EXISTS `markup`.`retiradas` (
  `id_retirada` INT NOT NULL AUTO_INCREMENT,
  `fk_colaborador` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` INT NULL DEFAULT NULL,
  `min` INT NULL DEFAULT NULL,
  `quant_total` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_retirada`),
  INDEX `fk_colaborador_idx` (`fk_colaborador` ASC),
  CONSTRAINT `fk_colaborador_3`
    FOREIGN KEY (`fk_colaborador`)
    REFERENCES `markup`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`contas_bancarias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`contas_bancarias` ;

CREATE TABLE IF NOT EXISTS `markup`.`contas_bancarias` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(250) NULL DEFAULT NULL,
  `agencia` VARCHAR(45) NULL DEFAULT NULL,
  `conta` VARCHAR(45) NULL DEFAULT NULL,
  `titular` VARCHAR(250) NULL DEFAULT NULL,
  `fk_credor` INT NULL DEFAULT NULL,
  `fk_fornecedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `fk_credor_2_idx` (`fk_credor` ASC),
  INDEX `fk_fornecedor_8_idx` (`fk_fornecedor` ASC),
  CONSTRAINT `fk_credor_2`
    FOREIGN KEY (`fk_credor`)
    REFERENCES `markup`.`credores` (`id_credor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_9`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `markup`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`fornecedor_x_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`fornecedor_x_produto` ;

CREATE TABLE IF NOT EXISTS `markup`.`fornecedor_x_produto` (
  `id_fornecedor_x_prod` INT NOT NULL AUTO_INCREMENT,
  `fk_fornecedor` INT NULL DEFAULT NULL,
  `fk_produto` INT NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fornecedor_x_prod`),
  INDEX `fk_fornecedor_idx` (`fk_fornecedor` ASC),
  INDEX `fk_produto_idx` (`fk_produto` ASC),
  CONSTRAINT `fk_fornecedor_1`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `markup`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_2`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `markup`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`despesas` ;

CREATE TABLE IF NOT EXISTS `markup`.`despesas` (
  `id_despesa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `valor_base` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_despesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`itens_de_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`itens_de_compra` ;

CREATE TABLE IF NOT EXISTS `markup`.`itens_de_compra` (
  `id_item_compra` INT NOT NULL AUTO_INCREMENT,
  `fk_compra` INT NULL DEFAULT NULL,
  `fk_fornecedor` INT NULL DEFAULT NULL,
  `fk_produto` INT NULL DEFAULT NULL,
  `fk_inventario` INT NULL DEFAULT NULL,
  `fk_despesa` INT NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `tipo` ENUM('ESTOQUE', 'INVENTARIO', 'DESPESA') NULL DEFAULT NULL,
  PRIMARY KEY (`id_item_compra`),
  INDEX `fk_compra_idx` (`fk_compra` ASC),
  INDEX `fk_fornecedor_idx` (`fk_fornecedor` ASC),
  INDEX `fk_produto_idx` (`fk_produto` ASC),
  INDEX `fk_inventario_idx` (`fk_inventario` ASC),
  INDEX `fk_despesa_2_idx` (`fk_despesa` ASC),
  CONSTRAINT `fk_compra_2`
    FOREIGN KEY (`fk_compra`)
    REFERENCES `markup`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_10`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `markup`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_4`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `markup`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_3`
    FOREIGN KEY (`fk_inventario`)
    REFERENCES `markup`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_2`
    FOREIGN KEY (`fk_despesa`)
    REFERENCES `markup`.`despesas` (`id_despesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`retirada_x_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`retirada_x_inventario` ;

CREATE TABLE IF NOT EXISTS `markup`.`retirada_x_inventario` (
  `id_retirada_x_inventario` INT NOT NULL AUTO_INCREMENT,
  `fk_retirada` INT NULL DEFAULT NULL,
  `fk_inventario` INT NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_retirada_x_inventario`),
  INDEX `fk_retirada_idx` (`fk_retirada` ASC),
  INDEX `fk_inventario_idx` (`fk_inventario` ASC),
  CONSTRAINT `fk_retirada_1`
    FOREIGN KEY (`fk_retirada`)
    REFERENCES `markup`.`retiradas` (`id_retirada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_2`
    FOREIGN KEY (`fk_inventario`)
    REFERENCES `markup`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`inventario_x_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`inventario_x_fornecedor` ;

CREATE TABLE IF NOT EXISTS `markup`.`inventario_x_fornecedor` (
  `id_fornecedor_inventario` INT NOT NULL AUTO_INCREMENT,
  `fk_inventario` INT NULL DEFAULT NULL,
  `fk_fornecedor` INT NULL DEFAULT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fornecedor_inventario`),
  INDEX `fk_inventario_idx` (`fk_inventario` ASC),
  INDEX `fk_fornecedor_idx` (`fk_fornecedor` ASC),
  CONSTRAINT `fk_inventario_1`
    FOREIGN KEY (`fk_inventario`)
    REFERENCES `markup`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_3`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `markup`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`aliquotas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`aliquotas` ;

CREATE TABLE IF NOT EXISTS `markup`.`aliquotas` (
  `id_aliquota` INT NOT NULL AUTO_INCREMENT,
  `valor_icms_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_pis_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_cofins_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_ipi_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_csll_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_irpj_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_comissao_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_administrativa_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `valor_issqn_porcento` VARCHAR(45) NULL DEFAULT NULL,
  `regime_tributario` ENUM('LUCRO_PRESUMIDO', 'LUCRO_REAL', 'SIMPLES', 'MEI') NULL DEFAULT NULL,
  PRIMARY KEY (`id_aliquota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`formas_de_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`formas_de_pagamento` ;

CREATE TABLE IF NOT EXISTS `markup`.`formas_de_pagamento` (
  `id_forma_pag` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `padrao` ENUM('SIM', 'NAO') NULL DEFAULT NULL,
  `tipo_parcela` ENUM('UNICO', 'PARCELADO') NULL DEFAULT NULL,
  `num_max_parcelas` INT NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL DEFAULT NULL,
  `tipo` ENUM('DINHEIRO', 'CREDITO', 'DEBITO', 'CREDIARIO') NULL DEFAULT NULL,
  PRIMARY KEY (`id_forma_pag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markup`.`movimentos_x_formas_de_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `markup`.`movimentos_x_formas_de_pagamento` ;

CREATE TABLE IF NOT EXISTS `markup`.`movimentos_x_formas_de_pagamento` (
  `id_mov_pag` INT NOT NULL AUTO_INCREMENT,
  `fk_movimento` INT NULL DEFAULT NULL,
  `fk_forma_de_pagamento` INT NULL DEFAULT NULL,
  `num_de_parcelas` INT NULL DEFAULT NULL,
  `data_primeiro_vencimento` DATE NULL DEFAULT NULL,
  `valor_total` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mov_pag`),
  INDEX `fk_movimento_idx` (`fk_movimento` ASC),
  INDEX `fk_forma_de_pagamento_idx` (`fk_forma_de_pagamento` ASC),
  CONSTRAINT `fk_movimento_2`
    FOREIGN KEY (`fk_movimento`)
    REFERENCES `markup`.`movimentos` (`id_movimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forma_de_pagamento_1`
    FOREIGN KEY (`fk_forma_de_pagamento`)
    REFERENCES `markup`.`formas_de_pagamento` (`id_forma_pag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
